### ISSUE TITLE
not enough free disk space?

### ISSUE THREAD

**Issue by calendulish** [uraimo/run-on-arch-action#129] opened 2023-08-05 11:47 UTC
I suddenly started getting this error today, I didn't make any changes to my config.
I'm building armv7 on archlinux

```2023-08-05T11:35:25.4711803Z ------
2023-08-05T11:35:25.4712514Z  > [3/3] RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh:
2023-08-05T11:35:25.4712935Z 7.325 checking keyring...
2023-08-05T11:35:25.4713337Z 7.747 checking package integrity...
2023-08-05T11:35:25.4714657Z 30.05 loading package files...
2023-08-05T11:35:25.4714935Z 32.19 checking for file conflicts...
2023-08-05T11:35:25.4715189Z 32.33 checking available disk space...
2023-08-05T11:35:25.4715506Z 32.59 error: Partition /etc/resolv.conf is mounted read only
2023-08-05T11:35:25.4715831Z 32.59 error: Partition /etc/hosts is mounted read only
2023-08-05T11:35:25.4716106Z 32.59 error: not enough free disk space
2023-08-05T11:35:25.4716432Z 32.59 error: failed to commit transaction (not enough free disk space)
2023-08-05T11:35:25.4716769Z 32.70 Errors occurred, no packages were upgraded.
2023-08-05T11:35:25.4717048Z ------
2023-08-05T11:35:25.4717284Z Dockerfile.armv7.archarm_latest:4
2023-08-05T11:35:25.4717577Z --------------------
2023-08-05T11:35:25.4717770Z    2 |     
2023-08-05T11:35:25.4718148Z    3 |     COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
2023-08-05T11:35:25.4718650Z    4 | >>> RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh
2023-08-05T11:35:25.4718962Z    5 |     
2023-08-05T11:35:25.4719187Z --------------------
2023-08-05T11:35:25.4791597Z ERROR: failed to solve: process "/bin/sh -c chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh" did not complete successfully: exit code: 1```

**Comment by martin-g** [comment] 2023-08-05 12:29
Hi,

Most probably the issue is with the host, I.e. Girhub runners.

**Comment by calendulish** [comment] 2023-08-10 10:23
> Hi, Most probably the issue is with the host, I.e. Girhub runners.

I moved the system update command (pacman -Syu) from the "install" parameter to "run" parameter, and it worked fine.

**Comment by uraimo** [comment] 2023-08-10 11:03
From that log it seems that the partition was being mounted as read-only for some reason, no idea about why this could be the case with that Arch container. Closing this, not an action bug.

**Closed by uraimo** 2023-08-10 11:03 UTC

**Comment by 67au** [comment] 2024-03-08 13:54
https://github.com/Alexpux/MSYS2-pacman/issues/59#issuecomment-659128464
it work fine too.
